export enum EnvironmentStatus {
  READY = "READY",
  CREATED = "CREATED",
  CONFIG_VALID = "CONFIG_VALID",
  PREPARING = "PREPARING",
  EXECUTING = "EXECUTING",
  PREPARATION_FAILED = "PREPARATION_FAILED",
  BROKEN = "BROKEN",
  CONFIG_INVALID = "CONFIG_INVALID",
  CLEANED = "CLEANED",
  CLEANING = "CLEANING",
  CLEAN_FAILED = "CLEAN_FAILED",
}
