import type { ButtonDesignTokens } from "@primeuix/themes/types/button";

export default {
  root: {
    borderRadius: "{form.field.border.radius}",
    roundedBorderRadius: "2rem",
    gap: "0.5rem",
    paddingX: "{form.field.padding.x}",
    paddingY: "{form.field.padding.y}",
    iconOnlyWidth: "2.0rem",
    sm: {
      fontSize: "0.875rem",
      paddingX: "0.5rem",
      paddingY: "0.25rem",
      iconOnlyWidth: "2.0rem",
    },
    lg: {
      fontSize: "1.125rem",
      paddingX: "0.75rem",
      paddingY: "0.5rem",
      iconOnlyWidth: "2.5rem",
    },
    label: {
      fontWeight: "500",
    },
    raisedShadow:
      "0 3px 1px -2px rgba(0, 0, 0, 0.2),0 2px 2px 0 rgba(0, 0, 0, 0.14),0 1px 5px 0 rgba(0, 0, 0, 0.12)",
    focusRing: {
      width: "{focus.ring.width}",
      style: "{focus.ring.style}",
      offset: "{focus.ring.offset}",
    },
    badgeSize: "1.0rem",
    transitionDuration: "{form.field.transition.duration}",
  },
  colorScheme: {
    light: {
      root: {
        primary: {
          background: "{primary.color}",
          hoverBackground: "{primary.hover.color}",
          activeBackground: "{primary.active.color}",
          borderColor: "{primary.color}",
          hoverBorderColor: "{primary.hover.color}",
          activeBorderColor: "{primary.active.color}",
          color: "{primary.contrast.color}",
          hoverColor: "{primary.contrast.color}",
          activeColor: "{primary.contrast.color}",
          focusRing: {
            color: "{primary.color}",
            shadow: "0 0 0 0 #00000000",
          },
        },
        secondary: {
          background: "{surface.100}",
          hoverBackground: "{surface.200}",
          activeBackground: "{surface.300}",
          borderColor: "{surface.100}",
          hoverBorderColor: "{surface.200}",
          activeBorderColor: "{surface.300}",
          color: "{surface.600}",
          hoverColor: "{surface.700}",
          activeColor: "{surface.800}",
          focusRing: {
            color: "{surface.600}",
            shadow: "0 0 0 0 #00000000",
          },
        },
        info: {
          background: "{info blue.500}",
          hoverBackground: "{info blue.600}",
          activeBackground: "{info blue.700}",
          borderColor: "{info blue.500}",
          hoverBorderColor: "{info blue.600}",
          activeBorderColor: "{info blue.700}",
          color: "#ffffff",
          hoverColor: "#ffffff",
          activeColor: "#ffffff",
          focusRing: {
            color: "{info blue.500}",
            shadow: "0 0 0 0 #00000000",
          },
        },
        success: {
          background: "{green.500}",
          hoverBackground: "{green.600}",
          activeBackground: "{green.700}",
          borderColor: "{green.500}",
          hoverBorderColor: "{green.600}",
          activeBorderColor: "{green.700}",
          color: "#ffffff",
          hoverColor: "#ffffff",
          activeColor: "#ffffff",
          focusRing: {
            color: "{green.500}",
            shadow: "0 0 0 0 #00000000",
          },
        },
        warn: {
          background: "{amber.500}",
          hoverBackground: "{amber.600}",
          activeBackground: "{amber.700}",
          borderColor: "{amber.500}",
          hoverBorderColor: "{amber.600}",
          activeBorderColor: "{amber.700}",
          color: "#ffffff",
          hoverColor: "#ffffff",
          activeColor: "#ffffff",
          focusRing: {
            color: "{amber.500}",
            shadow: "0 0 0 0 #00000000",
          },
        },
        help: {
          background: "{purple.500}",
          hoverBackground: "{purple.600}",
          activeBackground: "{purple.700}",
          borderColor: "{purple.500}",
          hoverBorderColor: "{purple.600}",
          activeBorderColor: "{purple.700}",
          color: "#ffffff",
          hoverColor: "#ffffff",
          activeColor: "#ffffff",
          focusRing: {
            color: "{purple.500}",
            shadow: "0 0 0 0 #00000000",
          },
        },
        danger: {
          background: "{red.500}",
          hoverBackground: "{red.600}",
          activeBackground: "{red.700}",
          borderColor: "{red.500}",
          hoverBorderColor: "{red.600}",
          activeBorderColor: "{red.700}",
          color: "#ffffff",
          hoverColor: "#ffffff",
          activeColor: "#ffffff",
          focusRing: {
            color: "{red.500}",
            shadow: "0 0 0 0 #00000000",
          },
        },
        contrast: {
          background: "{surface.950}",
          hoverBackground: "{surface.900}",
          activeBackground: "{surface.800}",
          borderColor: "{surface.950}",
          hoverBorderColor: "{surface.900}",
          activeBorderColor: "{surface.800}",
          color: "{surface.0}",
          hoverColor: "{surface.0}",
          activeColor: "{surface.0}",
          focusRing: {
            color: "{surface.950}",
            shadow: "0 0 0 0 #00000000",
          },
        },
      },
      outlined: {
        primary: {
          hoverBackground: "{primary.50}",
          activeBackground: "{primary.100}",
          borderColor: "{primary.200}",
          color: "{primary.color}",
        },
        secondary: {
          hoverBackground: "{surface.50}",
          activeBackground: "{surface.100}",
          borderColor: "{surface.200}",
          color: "{surface.500}",
        },
        success: {
          hoverBackground: "{green.50}",
          activeBackground: "{green.100}",
          borderColor: "{green.200}",
          color: "{green.500}",
        },
        info: {
          hoverBackground: "{info blue.50}",
          activeBackground: "{info blue.100}",
          borderColor: "{info blue.200}",
          color: "{info blue.500}",
        },
        warn: {
          hoverBackground: "{amber.50}",
          activeBackground: "{amber.100}",
          borderColor: "{amber.200}",
          color: "{amber.500}",
        },
        help: {
          hoverBackground: "{purple.50}",
          activeBackground: "{purple.100}",
          borderColor: "{purple.200}",
          color: "{purple.500}",
        },
        danger: {
          hoverBackground: "{red.50}",
          activeBackground: "{red.100}",
          borderColor: "{red.200}",
          color: "{red.500}",
        },
        contrast: {
          hoverBackground: "{surface.50}",
          activeBackground: "{surface.100}",
          borderColor: "{surface.700}",
          color: "{surface.950}",
        },
        plain: {
          hoverBackground: "{surface.50}",
          activeBackground: "{surface.100}",
          borderColor: "{surface.200}",
          color: "{surface.700}",
        },
      },
      text: {
        primary: {
          hoverBackground: "{primary.50}",
          activeBackground: "{primary.100}",
          color: "{primary.color}",
        },
        secondary: {
          hoverBackground: "{surface.50}",
          activeBackground: "{surface.100}",
          color: "{surface.500}",
        },
        success: {
          hoverBackground: "{green.50}",
          activeBackground: "{green.100}",
          color: "{green.500}",
        },
        info: {
          hoverBackground: "{info blue.50}",
          activeBackground: "{info blue.100}",
          color: "{info blue.500}",
        },
        warn: {
          hoverBackground: "{amber.50}",
          activeBackground: "{amber.100}",
          color: "{amber.500}",
        },
        help: {
          hoverBackground: "{purple.50}",
          activeBackground: "{purple.100}",
          color: "{purple.500}",
        },
        danger: {
          hoverBackground: "{red.50}",
          activeBackground: "{red.100}",
          color: "{red.500}",
        },
        contrast: {
          hoverBackground: "{surface.50}",
          activeBackground: "{surface.100}",
          color: "{surface.950}",
        },
        plain: {
          hoverBackground: "{surface.50}",
          activeBackground: "{surface.100}",
          color: "{surface.700}",
        },
      },
      link: {
        color: "{primary.color}",
        hoverColor: "{primary.color}",
        activeColor: "{primary.color}",
      },
    },
    dark: {
      root: {
        primary: {
          background: "{primary.color}",
          hoverBackground: "{primary.hover.color}",
          activeBackground: "{primary.active.color}",
          borderColor: "{primary.color}",
          hoverBorderColor: "{primary.hover.color}",
          activeBorderColor: "{primary.active.color}",
          color: "{primary.contrast.color}",
          hoverColor: "{primary.contrast.color}",
          activeColor: "{primary.contrast.color}",
          focusRing: {
            color: "{primary.color}",
            shadow: "0 0 0 0 #00000000",
          },
        },
        secondary: {
          background: "{surface.800}",
          hoverBackground: "{surface.700}",
          activeBackground: "{surface.600}",
          borderColor: "{surface.800}",
          hoverBorderColor: "{surface.700}",
          activeBorderColor: "{surface.600}",
          color: "{surface.300}",
          hoverColor: "{surface.200}",
          activeColor: "{surface.100}",
          focusRing: {
            color: "{surface.300}",
            shadow: "0 0 0 0 #00000000",
          },
        },
        info: {
          background: "{info blue.400}",
          hoverBackground: "{info blue.300}",
          activeBackground: "{info blue.200}",
          borderColor: "{info blue.400}",
          hoverBorderColor: "{info blue.300}",
          activeBorderColor: "{info blue.200}",
          color: "{info blue.950}",
          hoverColor: "{info blue.950}",
          activeColor: "{info blue.950}",
          focusRing: {
            color: "{info blue.400}",
            shadow: "0 0 0 0 #00000000",
          },
        },
        success: {
          background: "{green.400}",
          hoverBackground: "{green.300}",
          activeBackground: "{green.200}",
          borderColor: "{green.400}",
          hoverBorderColor: "{green.300}",
          activeBorderColor: "{green.200}",
          color: "{green.950}",
          hoverColor: "{green.950}",
          activeColor: "{green.950}",
          focusRing: {
            color: "{green.400}",
            shadow: "0 0 0 0 #00000000",
          },
        },
        warn: {
          background: "{amber.400}",
          hoverBackground: "{amber.300}",
          activeBackground: "{amber.200}",
          borderColor: "{amber.400}",
          hoverBorderColor: "{amber.300}",
          activeBorderColor: "{amber.200}",
          color: "{amber.950}",
          hoverColor: "{amber.950}",
          activeColor: "{amber.950}",
          focusRing: {
            color: "{amber.400}",
            shadow: "0 0 0 0 #00000000",
          },
        },
        help: {
          background: "{purple.400}",
          hoverBackground: "{purple.300}",
          activeBackground: "{purple.200}",
          borderColor: "{purple.400}",
          hoverBorderColor: "{purple.300}",
          activeBorderColor: "{purple.200}",
          color: "{purple.950}",
          hoverColor: "{purple.950}",
          activeColor: "{purple.950}",
          focusRing: {
            color: "{purple.400}",
            shadow: "0 0 0 0 #00000000",
          },
        },
        danger: {
          background: "{red.400}",
          hoverBackground: "{red.300}",
          activeBackground: "{red.200}",
          borderColor: "{red.400}",
          hoverBorderColor: "{red.300}",
          activeBorderColor: "{red.200}",
          color: "{red.950}",
          hoverColor: "{red.950}",
          activeColor: "{red.950}",
          focusRing: {
            color: "{red.400}",
            shadow: "0 0 0 0 #00000000",
          },
        },
        contrast: {
          background: "{surface.0}",
          hoverBackground: "{surface.100}",
          activeBackground: "{surface.200}",
          borderColor: "{surface.0}",
          hoverBorderColor: "{surface.100}",
          activeBorderColor: "{surface.200}",
          color: "{surface.950}",
          hoverColor: "{surface.950}",
          activeColor: "{surface.950}",
          focusRing: {
            color: "{surface.0}",
            shadow: "0 0 0 0 #00000000",
          },
        },
      },
      outlined: {
        primary: {
          hoverBackground:
            "color-mix(in srgb, {primary.color}, transparent 96%)",
          activeBackground:
            "color-mix(in srgb, {primary.color}, transparent 84%)",
          borderColor: "{primary.700}",
          color: "{primary.color}",
        },
        secondary: {
          hoverBackground: "rgba(255, 255, 255, 0.04)",
          activeBackground: "rgba(255, 255, 255, 0.16)",
          borderColor: "{surface.700}",
          color: "{surface.400}",
        },
        success: {
          hoverBackground: "color-mix(in srgb, {green.400}, transparent 96%)",
          activeBackground: "color-mix(in srgb, {green.400}, transparent 84%)",
          borderColor: "{green.700}",
          color: "{green.400}",
        },
        info: {
          hoverBackground:
            "color-mix(in srgb, {info blue.400}, transparent 96%)",
          activeBackground:
            "color-mix(in srgb, {info blue.400}, transparent 84%)",
          borderColor: "{info blue.700}",
          color: "{info blue.400}",
        },
        warn: {
          hoverBackground: "color-mix(in srgb, {amber.400}, transparent 96%)",
          activeBackground: "color-mix(in srgb, {amber.400}, transparent 84%)",
          borderColor: "{amber.700}",
          color: "{amber.400}",
        },
        help: {
          hoverBackground: "color-mix(in srgb, {purple.400}, transparent 96%)",
          activeBackground: "color-mix(in srgb, {purple.400}, transparent 84%)",
          borderColor: "{purple.700}",
          color: "{purple.400}",
        },
        danger: {
          hoverBackground: "color-mix(in srgb, {red.400}, transparent 96%)",
          activeBackground: "color-mix(in srgb, {red.400}, transparent 84%)",
          borderColor: "{red.700}",
          color: "{red.400}",
        },
        contrast: {
          hoverBackground: "{surface.800}",
          activeBackground: "{surface.700}",
          borderColor: "{surface.500}",
          color: "{surface.0}",
        },
        plain: {
          hoverBackground: "{surface.800}",
          activeBackground: "{surface.700}",
          borderColor: "{surface.600}",
          color: "{surface.0}",
        },
      },
      text: {
        primary: {
          hoverBackground:
            "color-mix(in srgb, {primary.color}, transparent 96%)",
          activeBackground:
            "color-mix(in srgb, {primary.color}, transparent 84%)",
          color: "{primary.color}",
        },
        secondary: {
          hoverBackground: "{surface.800}",
          activeBackground: "{surface.700}",
          color: "{surface.400}",
        },
        success: {
          hoverBackground: "color-mix(in srgb, {green.400}, transparent 96%)",
          activeBackground: "color-mix(in srgb, {green.400}, transparent 84%)",
          color: "{green.400}",
        },
        info: {
          hoverBackground:
            "color-mix(in srgb, {info blue.400}, transparent 96%)",
          activeBackground:
            "color-mix(in srgb, {info blue.400}, transparent 84%)",
          color: "{info blue.400}",
        },
        warn: {
          hoverBackground: "color-mix(in srgb, {amber.400}, transparent 96%)",
          activeBackground: "color-mix(in srgb, {amber.400}, transparent 84%)",
          color: "{amber.400}",
        },
        help: {
          hoverBackground: "color-mix(in srgb, {purple.400}, transparent 96%)",
          activeBackground: "color-mix(in srgb, {purple.400}, transparent 84%)",
          color: "{purple.400}",
        },
        danger: {
          hoverBackground: "color-mix(in srgb, {red.400}, transparent 96%)",
          activeBackground: "color-mix(in srgb, {red.400}, transparent 84%)",
          color: "{red.400}",
        },
        contrast: {
          hoverBackground: "{surface.800}",
          activeBackground: "{surface.700}",
          color: "{surface.0}",
        },
        plain: {
          hoverBackground: "{surface.800}",
          activeBackground: "{surface.700}",
          color: "{surface.0}",
        },
      },
      link: {
        color: "{primary.color}",
        hoverColor: "{primary.color}",
        activeColor: "{primary.color}",
      },
    },
  },
} satisfies ButtonDesignTokens;
