export enum ClientImpactNoteFieldType {
  RESOLUTION_TYPE = "RESOLUTION_TYPE",
  STREAM = "STREAM",
  REGION = "REGION",
  CBPM_L1_L2_L3 = "CBPM_L1_L2_L3",
  CBPM_L3_L4 = "CBPM_L3_L4",
  CBPM_L2_SCOPE = "CBPM_L2_SCOPE",
  IMPACTED_OUTPUTS = "IMPACTED_OUTPUTS",
  SOURCE_TYPE = "SOURCE_TYPE",
}
