export const MX_ICON_NAMES = {
  home: "home",
  arrow_back: "arrow_back",
  arrow_forward: "arrow_forward",
  arrow_upward: "arrow_upward",
  arrow_downward: "arrow_downward",
  expand_less: "expand_less",
  expand_more: "expand_more",
  chevron_left: "chevron_left",
  chevron_right: "chevron_right",
  keyboard_arrow_down: "keyboard_arrow_down",
  keyboard_arrow_left: "keyboard_arrow_left",
  keyboard_arrow_right: "keyboard_arrow_right",
  account_tree: "account_tree",
  draft: "draft",

  add: "add",
  add_circle: "add_circle",
  delete: "delete",
  edit: "edit",
  save: "save",
  content_copy: "content_copy",
  search: "search",
  refresh: "refresh",
  undo: "undo",
  send: "send",
  download: "download",
  upload: "upload",
  cloud_upload: "cloud_upload",
  link: "link",
  open_in_new: "open_in_new",
  visibility: "visibility",
  play_arrow: "play_arrow",
  play_circle: "play_circle",
  pause: "pause",
  stop: "stop",
  power_settings_new: "power_settings_new",
  dataset_linked: "dataset_linked",
  more_vert: "more_vert",

  check: "check",
  check_circle: "check_circle",
  close: "close",
  cancel: "cancel",
  block: "block",
  info: "info",
  error: "error",
  warning: "warning",
  help: "help",

  person: "person",
  person_add: "person_add",
  calendar_today: "calendar_today",
  schedule: "schedule",
  hourglass_empty: "hourglass_empty",
  description: "description",
  folder: "folder",
  folder_open: "folder_open",
  inbox: "inbox",
  assignment: "assignment",
  menu_book: "menu_book",
  language: "language",
  dns: "dns",
  storage: "storage",
  settings: "settings",
  build: "build",
  table_chart: "table_chart",
  show_chart: "show_chart",
  list: "list",
  menu: "menu",
  bolt: "bolt",
  flag: "flag",
  attach_file: "attach_file",
  history: "history",
  progress_activity: "progress_activity",
  circle: "circle",
  dark_mode: "dark_mode",
  light_mode: "light_mode",
  remove_circle: "remove_circle",
  remove_circle_outline: "remove_circle_outline",
  filter_alt: "filter_alt",
  filter_alt_off: "filter_alt_off",
  radar: "radar",
  bug_report: "bug_report",
  healing: "healing",
  mark_email_read: "mark_email_read",
  pending: "pending",
  access_time: "access_time",
  cleaning_services: "cleaning_services",
  archive: "archive",
} as const;

export type MxIconName = keyof typeof MX_ICON_NAMES;

export function resolveMaterialIconName(name: string): string | undefined {
  return (MX_ICON_NAMES as Record<string, string>)[name];
}
